# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'sorbet', :group => :development
gem 'sorbet-runtime'
gem 'rubocop-sorbet'
gem 'irb', '~> 1.1.0'
gem 'awesome_print'
